### ISSUE TITLE
The some sections that need to be more  Dynamic

### ISSUE THREAD

**Issue by hnicolus** [octs-SA/prooftv#1]
Lets create  a settings part on the Dashboard were we can easily update the information on the index section 
and th navbar should be more dynamic too .the titles ,so that the next time the client needs to update or rearrange the navbar its alot easier without them being able to read code

Those Lorem ipsum dolor sit amet.. will be hrd to replace line by line in code it would be better if you add it on the user panel

**Comment by Sjk-Lacoste** [comment]
yeah that is doable and easy
